# Cloudflare Pages configuration
name = "terapia-de-pareja-medellin"
compatibility_date = "2024-01-01"
pages_build_output_dir = "build"

# Build configuration for Cloudflare Pages
[build]
command = "npm run build:cloudflare"
publish = "build"