# Cloudflare Pages configuration
name = "terapia-de-pareja-medellin"
compatibility_date = "2024-01-01"

# This file is mainly for Wrangler CLI
# Cloudflare Pages build settings should be configured in the dashboard